export const servicesTranslations = {
  es: {
    "private-day-tours": {
      title: "Tours privados de un día",
      desc: "Tours privados de un día desde Viena a Austria y países vecinos.",
      longDesc: `<h1><strong>Tours privados de un día</strong></h1><p>Nuestros tours privados de un día desde Viena ofrecen la oportunidad perfecta para descubrir los destinos más hermosos de Austria y países vecinos con total comodidad y a su propio ritmo.</p><p>Disfrute de un viaje relajado con un chófer privado en Viena, un vehículo espacioso y flexibilidad completa durante todo el día.</p><h2><strong>Descubra Austria con comodidad</strong></h2><p>Austria ofrece paisajes impresionantes y destinos mundialmente famosos, ideales para viajes privados de un día. Los destinos populares incluyen Salzburgo, Hallstatt, el valle de Wachau, Melk, Graz, los Alpes austriacos y viajes de un día a Bratislava o Budapest.</p><h2><strong>Su horario, su ruta</strong></h2><p>En un tour privado de un día, usted decide cómo se desarrolla su día. Pase el tiempo que desee en cada parada, agregue destinos adicionales o ajuste su ruta de manera flexible. Su conductor apoyará sus planes y garantizará una experiencia suave y agradable.</p><h2><strong>Precios fijos y flexibilidad completa</strong></h2><p>Todos los precios para tours privados de un día se muestran de manera transparente con anticipación, sin sorpresas.</p>`
    },
    "hotel-transfers-vienna": {
      title: "Traslados de hotel en Viena",
      desc: "Traslados de hotel cómodos y confiables en Viena y en toda Austria.",
      longDesc: `<h1><strong>Traslados de hotel en Viena</strong></h1><p>Nuestros traslados de hotel en Viena ofrecen una forma cómoda y directa de viajar entre el aeropuerto de Viena, estaciones de tren y cualquier hotel en Viena o en toda Austria.</p><p>Ya sea que llegue después de un viaje largo o se prepare para su salida, nuestros conductores profesionales garantizan una experiencia puerta a puerta sin estrés, puntual y agradable.</p><p>Disfrute de vehículos limpios, servicio confiable y máximo confort en cada viaje.</p><h2><strong>Recogidas directas desde cualquier hotel</strong></h2><p>Ofrecemos traslados directos desde todos los hoteles principales en Viena y el área circundante. Su conductor lo estará esperando en la entrada del hotel para asistirle con su equipaje.</p><h2><strong>Precios fijos y sin cargos ocultos</strong></h2><p>Todos los precios de traslados de hotel son fijos y se muestran de manera transparente antes de la reserva. No hay cargos adicionales por equipaje, retrasos de tráfico o viajes nocturnos.</p>`
    },
    "long-distance-transfers": {
      title: "Traslados de larga distancia",
      desc: "Traslados privados cómodos de larga distancia en toda Austria y Europa.",
      longDesc: `<h1><strong>Traslados de larga distancia</strong></h1><p>Nuestros traslados de larga distancia ofrecen una forma cómoda, segura y sin estrés de viajar desde Viena a destinos en toda Austria y países vecinos.</p><p>Ya sea que se dirija a Salzburgo, Graz, Linz, Innsbruck, Hallstatt, o a Budapest, Bratislava, Praga, Múnich, Italia o Suiza, nuestro traslado privado profesional garantiza un viaje agradable con máximo confort.</p><h2><strong>Viajes cómodos más allá de Viena</strong></h2><p>Los viajes largos requieren un vehículo que sea espacioso, limpio y cómodo. Nuestra flota incluye sedanes, minivanes y vehículos para grupos más grandes, con amplio espacio para pasajeros y equipaje.</p><h2><strong>Servicio directo de puerta a puerta</strong></h2><p>Sin transferencias, sin conexiones, sin esperas. Lo recogemos en su ubicación deseada en Viena y lo llevamos directamente a su destino.</p><h2><strong>Precios fijos y sin cargos ocultos</strong></h2><p>Todas las tarifas de larga distancia se confirman con anticipación y se mantienen fijas, independientemente del tráfico, el tiempo de viaje o el clima. Siempre sabe el precio exacto antes de que comience su viaje.</p>`
    },
    "vienna-airport-taxi-fixed-price": {
      title: "Taxi del aeropuerto de Viena a precio fijo",
      desc: "Servicio de taxi confiable del aeropuerto de Viena a precio fijo garantizado sin cargos ocultos.",
      longDesc: `<h1><strong>Taxi del aeropuerto de Viena a precio fijo</strong></h1><p>Nuestro servicio de taxi del aeropuerto de Viena ofrece una forma cómoda, confiable y rentable de viajar entre el aeropuerto de Viena (VIE) y cualquier destino en la ciudad o en toda Austria.</p><p>Ya sea que llegue después de un vuelo largo o se prepare para su salida, nuestros conductores profesionales garantizan un viaje cómodo y eficiente con total transparencia.</p><h2><strong>Precios transparentes y fijos</strong></h2><p>Ofrecemos tarifas justas y competitivas de taxi con precios fijos garantizados. No hay sorpresas, no hay cargos ocultos. Nuestros taxis están equipados con aire acondicionado y Wi-Fi gratuito.</p><h2><strong>Servicio de taxi fiable</strong></h2><p>Reserve su taxi desde el aeropuerto de Viena hoy y viaje relajado con nuestro servicio de taxi confiable y profesional, disponible 24/7.</p>`
    },
    "vienna-airport-to-city-taxi": {
      title: "Servicio de taxi desde el aeropuerto de Viena al centro de la ciudad",
      desc: "Servicio de taxi confiable desde el aeropuerto de Viena (VIE) al centro de la ciudad con precios transparentes y conductores profesionales.",
      longDesc: `<h1><strong>Servicio de taxi desde el aeropuerto de Viena al centro de la ciudad</strong></h1><p>Llegar desde el aeropuerto internacional de Viena (VIE) al centro de la ciudad es fácil, cómodo y confiable con nuestro servicio de taxi profesional.</p><p>Nuestro servicio de taxi ofrece un viaje suave y sin estrés directamente a su destino, con un enfoque especial en la puntualidad, la comodidad y la satisfacción del cliente.</p><h2><strong>Viajes en taxi cómodos y eficientes</strong></h2><p>Evite el estrés del transporte público o la espera de servicios compartidos. Disfrute de un viaje en taxi privado de puerta a puerta desde el aeropuerto de Viena directamente a su hotel, oficina o cualquier dirección en el centro de la ciudad.</p><p>Nuestros vehículos modernos y conductores experimentados garantizan un viaje rápido, cómodo y relajado.</p><h2><strong>Tarifas justas y servicio de taxi transparente</strong></h2><p>Ofrecemos tarifas de taxi justas y competitivas sin costos ocultos. Recibirá una cotización clara y transparente antes de que comience su viaje.</p>`
    },
    "vienna-airport-transfer": {
      title: "Traslados del aeropuerto de Viena (VIE)",
      desc: "Traslados confiables y sin estrés entre el aeropuerto de Viena (VIE) y cualquier destino en Viena o en toda Austria.",
      longDesc: `<h1><strong>Traslados del aeropuerto de Viena (VIE)</strong></h1><p>Nuestro servicio de traslado del aeropuerto de Viena (VIE) ofrece una forma cómoda, confiable y sin estrés de viajar entre el aeropuerto de Viena y cualquier destino dentro de la ciudad o en toda Austria.</p><p>Ya sea que llegue o se vaya, nuestros conductores profesionales y amables se aseguran de que cada parte de su viaje sea suave, eficiente y perfectamente coordinada.</p><p>Con precios fijos, sin cargos ocultos y servicio completamente personalizado, esta es la forma más fácil de comenzar o terminar su viaje en Viena.</p><h2><strong>Llegada sin estrés al aeropuerto de Viena</strong></h2><p>Después de un vuelo largo, no desea esperar en una cola de taxi o tratar con transporte público. Su conductor lo estará esperando en la sala de llegadas con una pancarta con su nombre.</p><p>Recibirá 60 minutos de tiempo de espera complementario para máxima flexibilidad y comodidad a la llegada.</p><h2><strong>Traslados confiables para salidas</strong></h2><p>Cuando viaja al aeropuerto, nuestros conductores garantizan que llegue bien antes de su vuelo. Planeamos cuidadosamente cada ruta, teniendo en cuenta las condiciones del tráfico, las horas pico y el clima.</p>`
    },
    "vienna-city-transfers": {
      title: "Traslados por la ciudad de Viena",
      desc: "Traslados cómodos y confiables por la ciudad de Viena con conductores profesionales y precios fijos.",
      longDesc: `<h1><strong>Traslados por la ciudad de Viena</strong></h1><p>Nuestros traslados por la ciudad de Viena ofrecen una forma rápida, confiable y cómoda de viajar entre cualquier dos ubicaciones dentro de la ciudad.</p><p>Ya sea que esté en Viena por negocios, asistiendo a una reunión importante, o explorando los monumentos históricos y distritos modernos, nuestro servicio de traslado profesional garantiza un viaje sin estrés en todo momento.</p><p>En lugar de tratar con transporte público o buscar estacionamiento, relájese en un vehículo limpio y moderno con un conductor con licencia que conoce Viena de adentro hacia afuera.</p><h2><strong>Paseos cómodos para cualquier ocasión</strong></h2><p>Nuestro servicio de traslado por la ciudad en Viena es ideal para todo tipo de viajes: recogidas de hotel, viajes a la oficina, visitas a restaurantes, viajes de compras, citas médicas o eventos culturales.</p><h2><strong>Perfecto para viajeros de negocios</strong></h2><p>Viena es uno de los centros comerciales, de congresos y diplomáticos más importantes de Europa Central, por lo que la puntualidad es primordial. Nuestros conductores garantizan que siempre llegue a tiempo.</p><h2><strong>Seguro, limpio y completamente transparente</strong></h2><p>Todos los traslados son realizados por conductores experimentados, con licencia y profesionales. Nuestros vehículos se limpian regularmente y se mantienen meticulosamente.</p>`
    },
    "taxi-vienna-airport": {
      title: "Taxi del aeropuerto de Viena",
      desc: "Servicio de taxi rápido, seguro y confiable entre el aeropuerto de Viena (VIE) y cualquier destino en Viena o en toda Austria.",
      longDesc: `<h1><strong>Taxi del aeropuerto de Viena</strong></h1><p>Nuestro servicio de taxi en el aeropuerto de Viena ofrece una forma rápida, segura y confiable de viajar entre el aeropuerto de Viena (VIE) y cualquier destino dentro de la ciudad o en toda Austria.</p><p>Ya sea que llegue después de un vuelo largo o se dirija al aeropuerto para su salida, nuestros conductores profesionales garantizan un viaje suave y sin estrés de principio a fin.</p><p>Evite esperar transporte público o buscar un taxi. Su conductor estará listo exactamente cuando lo necesite.</p><h2><strong>Traslados cómodos al aeropuerto</strong></h2><p>Con nuestro servicio de taxi al aeropuerto, disfruta de servicio directo de puerta a puerta en vehículos limpios, modernos y cómodos. Lo ayudamos con su equipaje y nos adaptamos de manera flexible a sus necesidades.</p><h2><strong>Monitoreo de vuelos y tiempo de espera</strong></h2><p>Los retrasos en vuelos no son un problema. Monitoreamos su vuelo en tiempo real y ajustamos automáticamente la hora de recogida. También recibe 60 minutos de tiempo de espera complementario en el aeropuerto.</p><h2><strong>Precios fijos sin cargos ocultos</strong></h2><p>Todos los precios de taxi del aeropuerto se muestran con anticipación, sin sorpresas. El precio incluye recogida en el aeropuerto, tiempo de espera, servicio de equipaje y monitoreo de vuelos.</p>`
    },
    "private-chauffeur-vienna": {
      title: "Chófer privado en Viena",
      desc: "Servicio de chófer privado de lujo en Viena con soluciones de transporte personalizadas, discretas y flexibles.",
      longDesc: `<h1><strong>Chófer privado en Viena</strong></h1><p>Contratar un chófer privado en Viena es la solución ideal para viajeros que valoran la comodidad, la confiabilidad y una experiencia de viaje completamente personalizada.</p><p>Ya sea que necesite un viaje de punto a punto dentro de la ciudad, un chófer para todo el día, apoyo para viajes de negocios, o traslados de larga distancia dentro de Austria y países vecinos, nuestros conductores profesionales garantizan viajes suaves y sin estrés.</p><h2><strong>Viaje cómodo y sin estrés</strong></h2><p>Un chófer privado le ofrece máxima flexibilidad. Sin esperas, sin colas, sin buscar taxis. Su conductor llega exactamente cuando y dónde lo necesita, proporcionando un servicio de puerta a puerta cómodo. Nuestros vehículos son modernos, bien mantenidos y perfectamente equipados para viajes cortos y largos.</p><h2><strong>Perfecto para clientes empresariales y corporativos</strong></h2><p>Viena es uno de los centros comerciales y de conferencias más importantes de Europa Central. Con un chófer privado, puede viajar de manera eficiente entre reuniones, conferencias, hoteles y el aeropuerto de Viena sin perder tiempo valioso. Nuestros chóferes son discretos, puntuales y están especialmente capacitados para proporcionar servicio óptimo a clientes VIP y empresariales.</p><h2><strong>Servicio personalizado para cada ocasión</strong></h2><p>Ya sea una visita familiar, una ocasión especial, un viaje de compras o turismo en Viena y sus alrededores, su chófer privado se adaptará de manera flexible a sus planes. Asientos para niños, espacio de almacenamiento adicional o viajes con múltiples paradas están disponibles bajo solicitud.</p>`
    }
  },
  en: {
    "private-day-tours": {
      title: "Private day tours",
      desc: "Private day tours from Vienna to Austria and neighboring countries.",
      longDesc: `<h1><strong>Private day tours</strong></h1><p>Our private day tours from Vienna offer the perfect opportunity to discover the most beautiful destinations in Austria and neighboring countries in complete comfort and at your own pace.</p><p>Enjoy a relaxed journey with a private chauffeur in Vienna, a spacious vehicle, and complete flexibility throughout the day.</p><h2><strong>Discover Austria in comfort</strong></h2><p>Austria offers breathtaking landscapes and world-famous destinations, ideal for private day trips. Popular destinations include Salzburg, Hallstatt, the Wachau Valley, Melk, Graz, the Austrian Alps, and day trips to Bratislava or Budapest.</p><h2><strong>Your schedule, your route</strong></h2><p>On a private day tour, you decide how your day unfolds. Spend as much time as you like at each stop, add extra destinations, or flexibly adjust your route along the way. Your driver will support your plans and ensure a smooth and enjoyable experience.</p><h2><strong>Fixed prices & full flexibility</strong></h2><p>All prices for private day tours are displayed transparently in advance – no surprises.</p>`
    },
    "hotel-transfers-vienna": {
      title: "Hotel Transfers Vienna",
      desc: "Comfortable and reliable hotel transfers in Vienna and across Austria.",
      longDesc: `<h1><strong>Hotel Transfers Vienna</strong></h1><p>Our hotel transfers in Vienna offer a seamless and comfortable way to travel between Vienna Airport, train stations, and any hotel in Vienna or throughout Austria.</p><p>Whether you're arriving after a long journey or preparing for your departure, our professional drivers ensure a punctual, stress-free, and pleasant door-to-door experience.</p><p>Enjoy clean vehicles, reliable service, and maximum comfort on every journey.</p><h2><strong>Direct pick-ups from any hotel</strong></h2><p>We offer direct transfers from all major hotels in Vienna and the surrounding area. Your driver will be waiting for you at the hotel entrance to assist with your luggage.</p><h2><strong>Fixed prices & no hidden fees</strong></h2><p>All hotel transfer prices are fixed and displayed transparently before booking. There are no additional charges for luggage, traffic delays, or nighttime journeys.</p>`
    },
    "long-distance-transfers": {
      title: "Long-Distance Transfers",
      desc: "Comfortable long-distance private transfers across Austria and Europe.",
      longDesc: `<h1><strong>Long-Distance Transfers</strong></h1><p>Our long-distance transfers offer a comfortable, safe, and stress-free way to travel from Vienna to destinations throughout Austria and neighboring countries.</p><p>Whether you're going to Salzburg, Graz, Linz, Innsbruck, Hallstatt, or to Budapest, Bratislava, Prague, Munich, Italy, or Switzerland – our professional private transfer ensures a pleasant journey with maximum comfort.</p><h2><strong>Comfortable travel beyond Vienna</strong></h2><p>Long journeys require a vehicle that is spacious, clean, and comfortable. Our fleet includes sedans, minivans, and vehicles for larger groups – with ample space for passengers and luggage.</p><h2><strong>Direct door-to-door service</strong></h2><p>No transfers, no connections, no waiting. We pick you up at your desired location in Vienna and take you directly to your destination.</p><h2><strong>Fixed prices & no hidden fees</strong></h2><p>All long-distance fares are confirmed in advance and remain fixed – regardless of traffic, travel time, or weather. You always know the exact price before your journey begins.</p>`
    },
    "vienna-airport-taxi-fixed-price": {
      title: "Vienna Airport Taxi at Fixed Price",
      desc: "Reliable Vienna Airport taxi service at a guaranteed fixed price with no hidden fees.",
      longDesc: `<h1><strong>Vienna Airport Taxi at Fixed Price</strong></h1><p>Our Vienna Airport taxi service offers a comfortable, reliable, and cost-effective way to travel between Vienna Airport (VIE) and any destination in the city or throughout Austria.</p><p>Whether you're arriving after a long flight or preparing for your departure, our professional drivers guarantee a comfortable and efficient journey with complete transparency.</p><h2><strong>Transparent and fixed prices</strong></h2><p>We offer fair and competitive taxi fares with guaranteed fixed prices. No surprises, no hidden charges. Our taxis are equipped with air conditioning and free Wi-Fi, ensuring a pleasant and comfortable ride.</p><h2><strong>Reliable taxi service</strong></h2><p>Book your taxi from Vienna Airport today and travel relaxed with our reliable and professional taxi service, available 24/7.</p>`
    },
    "vienna-airport-to-city-taxi": {
      title: "Taxi Service from Vienna Airport to the City Center",
      desc: "Reliable taxi service from Vienna Airport (VIE) to the city center with transparent pricing and professional drivers.",
      longDesc: `<h1><strong>Taxi Service from Vienna Airport to the City Center</strong></h1><p>Getting from Vienna International Airport (VIE) to the city center is easy, comfortable, and reliable with our professional taxi service.</p><p>Our taxi service offers you a smooth and stress-free ride directly to your destination – with a special focus on punctuality, comfort, and customer satisfaction.</p><h2><strong>Comfortable and efficient taxi rides</strong></h2><p>Avoid the stress of public transport or waiting for ride-sharing services. Enjoy a private door-to-door taxi ride from Vienna Airport directly to your hotel, office, or any address in the city center.</p><p>Our modern and spacious vehicles and experienced drivers ensure a fast, comfortable, and relaxed journey.</p><h2><strong>Fair prices and transparent taxi service</strong></h2><p>We offer fair and competitive taxi fares with no hidden costs. You'll receive a clear and transparent price quote before your journey begins, so you always know what to expect.</p>`
    },
    "vienna-airport-transfer": {
      title: "Airport Transfers Vienna (VIE)",
      desc: "Reliable and stress-free airport transfers between Vienna Airport (VIE) and any destination in Vienna or across Austria.",
      longDesc: `<h1><strong>Airport Transfers Vienna (VIE)</strong></h1><p>Our Vienna Airport (VIE) transfer service offers a comfortable, reliable, and stress-free way to travel between Vienna Airport and any destination within the city or throughout Austria.</p><p>Whether you're arriving or departing, our professional and friendly drivers ensure that every part of your journey runs smoothly, efficiently, and perfectly coordinated.</p><p>With fixed prices, no hidden fees, and fully personalized service, this is the easiest way to begin or end your trip in Vienna.</p><h2><strong>Stress-free arrival at Vienna Airport</strong></h2><p>After a long flight, you don't want to wait in a taxi queue or deal with public transport. Your driver will be waiting for you in the arrivals hall with a name sign.</p><p>You'll receive 60 minutes of complimentary waiting time – for maximum flexibility and comfort upon arrival.</p><h2><strong>Reliable transfers for departures</strong></h2><p>When traveling to the airport, our drivers ensure you arrive well before your flight. We carefully plan every route, taking into account traffic conditions, peak hours, and weather.</p>`
    },
    "vienna-city-transfers": {
      title: "Vienna City Transfers",
      desc: "Comfortable and reliable city transfers within Vienna with professional drivers and fixed pricing.",
      longDesc: `<h1><strong>Vienna City Transfers</strong></h1><p>Our city transfers in Vienna offer a fast, reliable, and comfortable way to travel between any two locations within the city.</p><p>Whether you're in Vienna on business, attending an important meeting, or exploring the historical landmarks and modern districts, our professional transfer service guarantees a stress-free journey every time.</p><p>Instead of dealing with public transport or finding parking, relax in a clean, modern vehicle with a licensed driver who knows Vienna inside and out.</p><h2><strong>Comfortable rides for every occasion</strong></h2><p>Our city transfer service in Vienna is ideal for all types of journeys – hotel pick-ups, office commutes, restaurant visits, shopping trips, doctor's appointments, or cultural events.</p><h2><strong>Perfect for business travelers</strong></h2><p>Vienna is one of Central Europe's most important business, congress, and diplomatic centers – punctuality is therefore paramount. Our drivers ensure you always arrive on time.</p><h2><strong>Safe, clean and completely transparent</strong></h2><p>All transfers are carried out by experienced, licensed, and professional drivers. Our vehicles are regularly cleaned and meticulously maintained for your safety and comfort.</p>`
    },
    "taxi-vienna-airport": {
      title: "Taxi Vienna Airport",
      desc: "Fast, safe and reliable taxi service between Vienna Airport (VIE) and any destination in Vienna or across Austria.",
      longDesc: `<h1><strong>Taxi Vienna Airport</strong></h1><p>Our taxi service at Vienna Airport offers a fast, safe, and reliable way to travel between Vienna Airport (VIE) and any destination within the city or throughout Austria.</p><p>Whether you're arriving after a long flight or heading to the airport for your departure, our professional drivers ensure a smooth and stress-free journey from start to finish.</p><p>Avoid waiting for public transport or searching for a taxi – your driver will be ready exactly when you need them.</p><h2><strong>Comfortable airport transfers</strong></h2><p>With our airport taxi service, you'll enjoy direct door-to-door service in clean, modern, and comfortable vehicles. We assist with your luggage and flexibly adapt the journey to your needs.</p><h2><strong>Flight monitoring & waiting time</strong></h2><p>Flight delays are no problem. We monitor your flight in real time and automatically adjust the pick-up time. You also receive 60 minutes of complimentary waiting time at Vienna Airport.</p><h2><strong>Fixed prices with no hidden fees</strong></h2><p>All airport taxi prices are displayed in advance – no surprises, no extra costs. The price includes airport pickup, waiting time, baggage service, and flight monitoring.</p>`
    },
    "private-chauffeur-vienna": {
      title: "Private Chauffeur in Vienna",
      desc: "Luxury private chauffeur service in Vienna with personalized, discreet and flexible transportation solutions.",
      longDesc: `<h1><strong>Private Chauffeur in Vienna</strong></h1><p>Hiring a private chauffeur in Vienna is the ideal solution for travelers who value comfort, reliability, and a fully personalized travel experience.</p><p>Whether you need a point-to-point ride within the city, a chauffeur for the entire day, support for business trips, or long-distance transfers within Austria and neighboring countries, our professional drivers ensure smooth and stress-free journeys.</p><h2><strong>Comfortable & stress-free travel</strong></h2><p>A private chauffeur offers you maximum flexibility. No waiting, no queues, no searching for taxis. Your driver arrives exactly when and where you need them, providing a comfortable door-to-door service. Our vehicles are modern, well-maintained, and perfectly equipped for both short and long journeys.</p><h2><strong>Perfect for business and corporate clients</strong></h2><p>Vienna is one of Central Europe's most important business and conference centers. With a private chauffeur, you can travel efficiently between meetings, conferences, hotels, and Vienna Airport without wasting valuable time. Our chauffeurs are discreet, punctual, and specially trained to provide optimal service.</p><h2><strong>Personalized service for every occasion</strong></h2><p>Whether it's a family visit, a special occasion, a shopping trip, or sightseeing in and around Vienna – your private chauffeur will flexibly adapt to your plans. Child seats, additional storage space, or trips with multiple stops are available upon request.</p>`
    }
  },
  fr: {
    "private-day-tours": {
      title: "Tours privés d'une journée",
      desc: "Tours privés d'une journée depuis Vienne vers l'Autriche et les pays voisins.",
      longDesc: `<h1><strong>Tours privés d'une journée</strong></h1><p>Nos tours privés d'une journée depuis Vienne offrent l'occasion parfaite de découvrir les plus beaux pays d'Autriche et des pays voisins en tout confort et à votre propre rythme.</p><p>Profitez d'un voyage relaxant avec un chauffeur privé à Vienne, un véhicule spacieux et une flexibilité complète tout au long de la journée.</p><h2><strong>Découvrez l'Autriche en confort</strong></h2><p>L'Autriche offre des paysages à couper le souffle et des destinations renommées dans le monde, idéales pour les voyages privés d'une journée. Les destinations populaires incluent Salzbourg, Hallstatt, la vallée de Wachau, Melk, Graz, les Alpes autrichiennes et les excursions d'une journée à Bratislava ou Budapest.</p><h2><strong>Votre horaire, votre itinéraire</strong></h2><p>Lors d'un tour privé d'une journée, vous décidez comment votre journée se déroulera. Passez autant de temps que vous le souhaitez à chaque arrêt, ajoutez des destinations supplémentaires ou ajustez votre itinéraire de manière flexible en cours de route. Votre chauffeur soutient vos plans et garantit une expérience douce et agréable.</p><h2><strong>Prix fixes et flexibilité complète</strong></h2><p>Tous les prix des tours privés d'une journée sont affichés de manière transparente à l'avance, sans surprise.</p>`
    },
    "hotel-transfers-vienna": {
      title: "Transferts hôtel à Vienne",
      desc: "Transferts hôtel confortables et fiables à Vienne et dans toute l'Autriche.",
      longDesc: `<h1><strong>Transferts hôtel à Vienne</strong></h1><p>Nos transferts hôtel à Vienne offrent un moyen transparent et confortable de voyager entre l'aéroport de Vienne, les gares et tout hôtel de Vienne ou d'Autriche.</p><p>Que vous arriviez après un long voyage ou que vous prépariez votre départ, nos chauffeurs professionnels garantissent une expérience de porte à porte ponctuelle, sans stress et agréable.</p><p>Profitez de véhicules propres, d'un service fiable et du confort maximum à chaque voyage.</p><h2><strong>Prises en charge directes depuis n'importe quel hôtel</strong></h2><p>Nous proposons des transferts directs depuis tous les principaux hôtels de Vienne et des environs. Votre chauffeur vous attendra à l'entrée de l'hôtel pour vous assister avec vos bagages.</p><h2><strong>Prix fixes et pas de frais cachés</strong></h2><p>Tous les prix des transferts hôtel sont fixes et affichés de manière transparente avant la réservation. Il n'y a pas de frais supplémentaires pour les bagages, les retards de circulation ou les voyages de nuit.</p>`
    },
    "long-distance-transfers": {
      title: "Transferts longue distance",
      desc: "Transferts privés confortables de longue distance dans toute l'Autriche et l'Europe.",
      longDesc: `<h1><strong>Transferts longue distance</strong></h1><p>Nos transferts longue distance offrent un moyen confortable, sûr et sans stress de voyager de Vienne vers des destinations dans toute l'Autriche et les pays voisins.</p><p>Que vous vous rendiez à Salzbourg, Graz, Linz, Innsbruck, Hallstatt, ou à Budapest, Bratislava, Prague, Munich, l'Italie ou la Suisse, notre transfert privé professionnel garantit un voyage agréable avec un confort maximal.</p><h2><strong>Voyage confortable au-delà de Vienne</strong></h2><p>Les longs trajets nécessitent un véhicule spacieux, propre et confortable. Notre flotte comprend des berlines, des minibus et des véhicules pour les plus grands groupes, avec amplement d'espace pour les passagers et les bagages.</p><h2><strong>Service porte-à-porte direct</strong></h2><p>Pas de transferts, pas de connexions, pas d'attente. Nous vous prenons à votre endroit souhaité à Vienne et vous conduisons directement à votre destination.</p><h2><strong>Prix fixes et pas de frais cachés</strong></h2><p>Tous les tarifs longue distance sont confirmés à l'avance et restent fixes, quels que soient le trafic, la durée du voyage ou la météo. Vous connaissez toujours le prix exact avant le début de votre voyage.</p>`
    },
    "vienna-airport-taxi-fixed-price": {
      title: "Taxi aéroport de Vienne à prix fixe",
      desc: "Service de taxi fiable de l'aéroport de Vienne à prix fixe garanti sans frais cachés.",
      longDesc: `<h1><strong>Taxi aéroport de Vienne à prix fixe</strong></h1><p>Notre service de taxi de l'aéroport de Vienne offre un moyen confortable, fiable et rentable de voyager entre l'aéroport de Vienne (VIE) et n'importe quelle destination en ville ou dans toute l'Autriche.</p><p>Que vous arriviez après un vol long ou que vous prépariez votre départ, nos chauffeurs professionnels garantissent un voyage confortable et efficace avec une transparence totale.</p><h2><strong>Prix transparents et fixes</strong></h2><p>Nous proposons des tarifs de taxi justes et compétitifs à prix fixe garanti. Pas de surprise, pas de frais cachés. Nos taxis sont équipés de climatisation et du Wi-Fi gratuit.</p><h2><strong>Service de taxi fiable</strong></h2><p>Réservez votre taxi depuis l'aéroport de Vienne aujourd'hui et voyagez en toute tranquillité avec notre service de taxi fiable et professionnel, disponible 24/7.</p>`
    },
    "vienna-airport-to-city-taxi": {
      title: "Service de taxi de l'aéroport de Vienne vers le centre-ville",
      desc: "Service de taxi fiable de l'aéroport de Vienne (VIE) vers le centre-ville avec prix transparents et chauffeurs professionnels.",
      longDesc: `<h1><strong>Service de taxi de l'aéroport de Vienne vers le centre-ville</strong></h1><p>Se rendre de l'aéroport international de Vienne (VIE) au centre-ville est facile, confortable et fiable grâce à notre service de taxi professionnel.</p><p>Notre service de taxi vous offre un trajet lisse et sans stress directement vers votre destination avec un accent particulier sur la ponctualité, le confort et la satisfaction du client.</p><h2><strong>Trajets en taxi confortables et efficaces</strong></h2><p>Évitez le stress des transports en commun ou l'attente de services de covoiturage. Profitez d'un trajet en taxi privé de porte à porte de l'aéroport de Vienne directement à votre hôtel, bureau ou n'importe quelle adresse du centre-ville.</p><p>Nos véhicules modernes et spacieux et nos chauffeurs expérimentés garantissent un trajet rapide, confortable et détendu.</p><h2><strong>Tarifs justes et service de taxi transparent</strong></h2><p>Nous proposons des tarifs de taxi justes et compétitifs sans frais cachés. Vous recevrez un devis clair et transparent avant le début de votre trajet.</p>`
    },
    "vienna-airport-transfer": {
      title: "Transferts aéroport de Vienne (VIE)",
      desc: "Transferts aéroport fiables et sans stress entre l'aéroport de Vienne (VIE) et n'importe quelle destination à Vienne ou en Autriche.",
      longDesc: `<h1><strong>Transferts aéroport de Vienne (VIE)</strong></h1><p>Notre service de transfert de l'aéroport de Vienne (VIE) offre un moyen confortable, fiable et sans stress de voyager entre l'aéroport de Vienne et n'importe quelle destination dans la ville ou dans toute l'Autriche.</p><p>Que vous arriviez ou que vous repartiez, nos chauffeurs professionnels et amicaux s'assurent que chaque partie de votre voyage se déroule sans accroc, efficacement et parfaitement coordonnée.</p><p>Avec des prix fixes, aucun frais caché et un service complètement personnalisé, c'est le moyen le plus facile de commencer ou de terminer votre voyage à Vienne.</p><h2><strong>Arrivée sans stress à l'aéroport de Vienne</strong></h2><p>Après un long vol, vous ne voulez pas attendre dans une queue de taxi ni traiter avec les transports en commun. Votre chauffeur vous attendra dans la salle des arrivées avec une pancarte avec votre nom.</p><p>Vous recevrez 60 minutes de temps d'attente gratuit – pour une flexibilité et un confort maximum à votre arrivée.</p><h2><strong>Transferts fiables pour les départs</strong></h2><p>Lorsque vous vous rendez à l'aéroport, nos chauffeurs s'assurent que vous arrivez bien avant votre vol. Nous planifions soigneusement chaque trajet en tenant compte des conditions de circulation, des heures de pointe et de la météo.</p>`
    },
    "vienna-city-transfers": {
      title: "Transferts en ville à Vienne",
      desc: "Transferts en ville confortables et fiables à Vienne avec chauffeurs professionnels et prix fixes.",
      longDesc: `<h1><strong>Transferts en ville à Vienne</strong></h1><p>Nos transferts en ville à Vienne offrent un moyen rapide, fiable et confortable de voyager entre deux endroits quelconques dans la ville.</p><p>Que vous soyez à Vienne pour affaires, assistant à une réunion importante ou explorant les monuments historiques et les quartiers modernes, notre service de transfert professionnel garantit un voyage sans stress à chaque fois.</p><p>Au lieu de traiter avec les transports en commun ou de chercher du stationnement, détendez-vous dans un véhicule propre et moderne avec un chauffeur autorisé qui connaît Vienne de l'intérieur.</p><h2><strong>Trajets confortables pour chaque occasion</strong></h2><p>Notre service de transfert en ville à Vienne est idéal pour tous types de trajets : prises en charge d'hôtel, trajets entre bureaux, visites de restaurants, sorties shopping, rendez-vous médicaux ou événements culturels.</p><h2><strong>Parfait pour les voyageurs d'affaires</strong></h2><p>Vienne est l'un des centres économiques, de congrès et diplomatiques les plus importants d'Europe centrale. La ponctualité est donc primordiale. Nos conducteurs garantissent que vous arrivez toujours à l'heure.</p><h2><strong>Sûr, propre et complètement transparent</strong></h2><p>Tous les transferts sont effectués par des chauffeurs expérimentés, agréés et professionnels. Nos véhicules sont régulièrement nettoyés et méticulouspement entretenus.</p>`
    },
    "taxi-vienna-airport": {
      title: "Taxi aéroport de Vienne",
      desc: "Service de taxi rapide, sûr et fiable entre l'aéroport de Vienne (VIE) et n'importe quelle destination à Vienne ou en Autriche.",
      longDesc: `<h1><strong>Taxi aéroport de Vienne</strong></h1><p>Notre service de taxi à l'aéroport de Vienne offre un moyen rapide, sûr et fiable de voyager entre l'aéroport de Vienne (VIE) et n'importe quelle destination en ville ou dans toute l'Autriche.</p><p>Que vous arriviez après un long vol ou que vous vous rendiez à l'aéroport pour votre départ, nos chauffeurs professionnels garantissent un trajet lisse et sans stress de bout en bout.</p><p>Évitez d'attendre les transports en commun ou de chercher un taxi. Votre chauffeur sera prêt exactement quand vous en aurez besoin.</p><h2><strong>Transferts confortables à l'aéroport</strong></h2><p>Avec notre service de taxi à l'aéroport, vous profitez d'un service de porte à porte direct dans des véhicules propres, modernes et confortables. Nous vous aidons avec vos bagages et nous adaptons de manière flexible à vos besoins.</p><h2><strong>Suivi des vols et temps d'attente</strong></h2><p>Les retards de vol ne sont pas un problème. Nous surveillons votre vol en temps réel et ajustons automatiquement l'heure de prise en charge. Vous recevez également 60 minutes de temps d'attente gratuit à l'aéroport de Vienne.</p><h2><strong>Prix fixes sans frais cachés</strong></h2><p>Tous les prix des taxis à l'aéroport sont affichés à l'avance, sans surprise, sans frais supplémentaires. Le prix comprend la prise en charge à l'aéroport, le temps d'attente, le service des bagages et le suivi des vols.</p>`
    },
    "private-chauffeur-vienna": {
      title: "Chauffeur privé à Vienne",
      desc: "Service de chauffeur privé luxe à Vienne avec solutions de transport personnalisées, discrètes et flexibles.",
      longDesc: `<h1><strong>Chauffeur privé à Vienne</strong></h1><p>Embaucher un chauffeur privé à Vienne est la solution idéale pour les voyageurs qui apprécient le confort, la fiabilité et une expérience de voyage complètement personnalisée.</p><p>Que vous ayez besoin d'un trajet d'un point à un autre dans la ville, d'un chauffeur pour la journée entière, d'un soutien pour les voyages d'affaires, ou de transferts longue distance dans toute l'Autriche et les pays voisins, nos chauffeurs professionnels garantissent des trajets sans accroc et sans stress.</p><h2><strong>Voyage confortable et sans stress</strong></h2><p>Un chauffeur privé vous offre une flexibilité maximale. Pas d'attente, pas de files d'attente, pas de recherche de taxis. Votre chauffeur arrive exactement quand et où vous en avez besoin, offrant un service de porte à porte confortable. Nos véhicules sont modernes, bien entretenus et parfaitement équipés pour les trajets courts et longs.</p><h2><strong>Parfait pour les clients commerciaux et corporatifs</strong></h2><p>Vienne est l'un des centres commerciaux et de congrès les plus importants d'Europe centrale. Avec un chauffeur privé, vous pouvez voyager efficacement entre réunions, conférences, hôtels et l'aéroport de Vienne sans gaspiller du temps précieux. Nos chauffeurs sont discrets, ponctuels et spécialement formés pour offrir un service optimal.</p><h2><strong>Service personnalisé pour chaque occasion</strong></h2><p>Qu'il s'agisse d'une visite familiale, d'une occasion spéciale, d'un voyage shopping ou de sightseeing à Vienne et ses environs, votre chauffeur privé s'adaptera de manière flexible à vos plans. Des sièges pour enfants, de l'espace de rangement supplémentaire ou des trajets avec plusieurs arrêts sont disponibles sur demande.</p>`
    }
  },
  it: {
    "private-day-tours": {
      title: "Tour privati di un giorno",
      desc: "Tour privati di un giorno da Vienna verso l'Austria e i paesi vicini.",
      longDesc: `<h1><strong>Tour privati di un giorno</strong></h1><p>I nostri tour privati di un giorno da Vienna offrono l'occasione perfetta per scoprire le destinazioni più belle dell'Austria e dei paesi vicini in totale comodità e al vostro ritmo.</p><p>Godete di un viaggio rilassato con un autista privato a Vienna, un veicolo spazioso e una flessibilità completa durante tutta la giornata.</p><h2><strong>Scopri l'Austria in comodità</strong></h2><p>L'Austria offre paesaggi mozzafiato e destinazioni di fama mondiale, ideali per viaggi privati di un giorno. Le destinazioni popolari includono Salisburgo, Hallstatt, la valle di Wachau, Melk, Graz, le Alpi austriache e gite di un giorno a Bratislava o Budapest.</p><h2><strong>Il vostro orario, il vostro percorso</strong></h2><p>Durante un tour privato di un giorno, voi decidete come si svolge la vostra giornata. Passate tutto il tempo che desiderate a ogni tappa, aggiungete destinazioni extra o regolate il vostro percorso in modo flessibile lungo il tragitto. Il vostro autista supporterà i vostri piani e garantirà un'esperienza fluida e piacevole.</p><h2><strong>Prezzi fissi e flessibilità completa</strong></h2><p>Tutti i prezzi dei tour privati di un giorno sono visualizzati in modo trasparente in anticipo, senza sorprese.</p>`
    },
    "hotel-transfers-vienna": {
      title: "Trasferimenti alberghieri a Vienna",
      desc: "Trasferimenti alberghieri comodi e affidabili a Vienna e in tutta l'Austria.",
      longDesc: `<h1><strong>Trasferimenti alberghieri a Vienna</strong></h1><p>I nostri trasferimenti alberghieri a Vienna offrono un modo trasparente e confortevole di viaggiare tra l'aeroporto di Vienna, le stazioni ferroviarie e qualsiasi hotel a Vienna o in Austria.</p><p>Che arriviate dopo un lungo viaggio o vi prepariate alla partenza, i nostri autisti professionisti garantiscono un'esperienza puntuale, senza stress e piacevole da porta a porta.</p><p>Godete di veicoli puliti, servizio affidabile e il massimo comfort ad ogni viaggio.</p><h2><strong>Prelievi diretti da qualsiasi hotel</strong></h2><p>Offriamo trasferimenti diretti da tutti i principali hotel di Vienna e i dintorni. Il vostro autista vi aspetterà all'ingresso dell'hotel per assistervi con i vostri bagagli.</p><h2><strong>Prezzi fissi e nessun costo nascosto</strong></h2><p>Tutti i prezzi dei trasferimenti alberghieri sono fissi e visualizzati in modo trasparente prima della prenotazione. Non ci sono costi aggiuntivi per i bagagli, i ritardi del traffico o i viaggi notturni.</p>`
    },
    "long-distance-transfers": {
      title: "Trasferimenti a lunga distanza",
      desc: "Trasferimenti privati comodi a lunga distanza in tutta l'Austria e l'Europa.",
      longDesc: `<h1><strong>Trasferimenti a lunga distanza</strong></h1><p>I nostri trasferimenti a lunga distanza offrono un modo confortevole, sicuro e senza stress di viaggiare da Vienna verso destinazioni in tutta l'Austria e i paesi vicini.</p><p>Che vi rechiate a Salisburgo, Graz, Linz, Innsbruck, Hallstatt, o a Budapest, Bratislava, Praga, Monaco, l'Italia o la Svizzera, il nostro trasferimento privato professionale garantisce un viaggio piacevole con il massimo comfort.</p><h2><strong>Viaggio confortevole oltre Vienna</strong></h2><p>I viaggi lunghi richiedono un veicolo spazioso, pulito e confortevole. La nostra flotta include berline, minivan e veicoli per gruppi più grandi, con ampio spazio per passeggeri e bagagli.</p><h2><strong>Servizio diretto da porta a porta</strong></h2><p>Nessun trasferimento, nessuna coincidenza, nessuna attesa. Vi riprendiamo dalla vostra posizione desiderata a Vienna e vi portiamo direttamente a destinazione.</p><h2><strong>Prezzi fissi e nessun costo nascosto</strong></h2><p>Tutte le tariffe a lunga distanza sono confermate in anticipo e rimangono fisse, indipendentemente dal traffico, dal tempo di viaggio o dal clima. Conoscete sempre il prezzo esatto prima dell'inizio del vostro viaggio.</p>`
    },
    "vienna-airport-taxi-fixed-price": {
      title: "Taxi aeroporto di Vienna a prezzo fisso",
      desc: "Servizio di taxi affidabile dell'aeroporto di Vienna a prezzo fisso garantito senza costi nascosti.",
      longDesc: `<h1><strong>Taxi aeroporto di Vienna a prezzo fisso</strong></h1><p>Il nostro servizio di taxi dell'aeroporto di Vienna offre un modo confortevole, affidabile e conveniente di viaggiare tra l'aeroporto di Vienna (VIE) e qualsiasi destinazione in città o in tutta l'Austria.</p><p>Che arriviate dopo un lungo volo o vi prepariate per la vostra partenza, i nostri autisti professionisti garantiscono un viaggio confortevole ed efficiente con completa trasparenza.</p><h2><strong>Prezzi trasparenti e fissi</strong></h2><p>Offriamo tariffe di taxi eque e competitive a prezzo fisso garantito. Nessuna sorpresa, nessun costo nascosto. I nostri taxi sono equipaggiati con aria condizionata e Wi-Fi gratuito.</p><h2><strong>Servizio di taxi affidabile</strong></h2><p>Prenotate il vostro taxi dall'aeroporto di Vienna oggi e viaggiate in tutta tranquillità con il nostro servizio di taxi affidabile e professionale, disponibile 24/7.</p>`
    },
    "vienna-airport-to-city-taxi": {
      title: "Servizio taxi dall'aeroporto di Vienna al centro città",
      desc: "Servizio taxi affidabile dall'aeroporto di Vienna (VIE) al centro città con prezzi trasparenti e autisti professionisti.",
      longDesc: `<h1><strong>Servizio taxi dall'aeroporto di Vienna al centro città</strong></h1><p>Raggiungere il centro città dall'aeroporto internazionale di Vienna (VIE) è facile, confortevole e affidabile con il nostro servizio di taxi professionale.</p><p>Il nostro servizio di taxi vi offre un viaggio fluido e senza stress direttamente verso la vostra destinazione, con un particolare focus sulla puntualità, il comfort e la soddisfazione del cliente.</p><h2><strong>Corse in taxi confortevoli ed efficienti</strong></h2><p>Evitate lo stress del trasporto pubblico o l'attesa di servizi di ridesharing. Godete di una corsa in taxi privata da porta a porta dall'aeroporto di Vienna direttamente al vostro hotel, ufficio o qualsiasi indirizzo nel centro città.</p><p>I nostri veicoli moderni e spaziosi e gli autisti esperti garantiscono un viaggio veloce, confortevole e rilassato.</p><h2><strong>Tariffe eque e servizio di taxi trasparente</strong></h2><p>Offriamo tariffe di taxi eque e competitive senza costi nascosti. Riceverete un preventivo chiaro e trasparente prima dell'inizio del vostro viaggio.</p>`
    },
    "vienna-airport-transfer": {
      title: "Trasferimenti aeroporto di Vienna (VIE)",
      desc: "Trasferimenti aeroporto affidabili e senza stress tra l'aeroporto di Vienna (VIE) e qualsiasi destinazione a Vienna o in tutta l'Austria.",
      longDesc: `<h1><strong>Trasferimenti aeroporto di Vienna (VIE)</strong></h1><p>Il nostro servizio di trasferimento dell'aeroporto di Vienna (VIE) offre un modo confortevole, affidabile e senza stress di viaggiare tra l'aeroporto di Vienna e qualsiasi destinazione all'interno della città o in tutta l'Austria.</p><p>Che arriviate o partiate, i nostri autisti professionisti e cordiali si assicurano che ogni parte del vostro viaggio si svolga in modo fluido, efficiente e perfettamente coordinato.</p><p>Con prezzi fissi, nessun costo nascosto e servizio completamente personalizzato, questo è il modo più facile per iniziare o terminare il vostro viaggio a Vienna.</p><h2><strong>Arrivo senza stress all'aeroporto di Vienna</strong></h2><p>Dopo un lungo volo, non desiderate aspettare in una coda di taxi o affrontare il trasporto pubblico. Il vostro autista vi aspetterà nella sala degli arrivi con un cartello con il vostro nome.</p><p>Riceverete 60 minuti di tempo d'attesa gratuito – per la massima flessibilità e comfort all'arrivo.</p><h2><strong>Trasferimenti affidabili per le partenze</strong></h2><p>Quando vi recate all'aeroporto, i nostri autisti si assicurano che arriviate ben prima del vostro volo. Pianifichiamo attentamente ogni percorso, tenendo conto delle condizioni del traffico, delle ore di punta e del meteo.</p>`
    },
    "vienna-city-transfers": {
      title: "Trasferimenti in città a Vienna",
      desc: "Trasferimenti in città comodi e affidabili a Vienna con autisti professionisti e prezzi fissi.",
      longDesc: `<h1><strong>Trasferimenti in città a Vienna</strong></h1><p>I nostri trasferimenti in città a Vienna offrono un modo veloce, affidabile e confortevole di viaggiare tra due località qualsiasi all'interno della città.</p><p>Che siate a Vienna per affari, partecipate a una riunione importante o esplorando i monumenti storici e i quartieri moderni, il nostro servizio di trasferimento professionale garantisce un viaggio senza stress ogni volta.</p><p>Invece di affrontare il trasporto pubblico o cercare parcheggio, rilassatevi in un veicolo pulito e moderno con un autista patentato che conosce Vienna dentro e fuori.</p><h2><strong>Corse confortevoli per ogni occasione</strong></h2><p>Il nostro servizio di trasferimento in città a Vienna è ideale per tutti i tipi di viaggi: ritiri da hotel, navette ufficio, visite a ristoranti, spedizioni di shopping, appuntamenti medici o eventi culturali.</p><h2><strong>Perfetto per i viaggiatori d'affari</strong></h2><p>Vienna è uno dei più importanti centri economici, congressuali e diplomatici dell'Europa centrale. La puntualità è quindi essenziale. I nostri autisti garantiscono che arriviate sempre puntualmente.</p><h2><strong>Sicuro, pulito e completamente trasparente</strong></h2><p>Tutti i trasferimenti sono effettuati da autisti esperti, patentati e professionisti. I nostri veicoli vengono regolarmente puliti e meticulosamente mantenuti.</p>`
    },
    "taxi-vienna-airport": {
      title: "Taxi aeroporto di Vienna",
      desc: "Servizio di taxi veloce, sicuro e affidabile tra l'aeroporto di Vienna (VIE) e qualsiasi destinazione a Vienna o in tutta l'Austria.",
      longDesc: `<h1><strong>Taxi aeroporto di Vienna</strong></h1><p>Il nostro servizio di taxi all'aeroporto di Vienna offre un modo veloce, sicuro e affidabile di viaggiare tra l'aeroporto di Vienna (VIE) e qualsiasi destinazione all'interno della città o in tutta l'Austria.</p><p>Che arriviate dopo un lungo volo o vi dirigiate all'aeroporto per la vostra partenza, i nostri autisti professionisti garantiscono un viaggio fluido e senza stress dall'inizio alla fine.</p><p>Evitate di aspettare il trasporto pubblico o cercare un taxi. Il vostro autista sarà pronto esattamente quando lo necessite.</p><h2><strong>Trasferimenti comfortevoli all'aeroporto</strong></h2><p>Con il nostro servizio di taxi all'aeroporto, godrete di un servizio diretto da porta a porta in veicoli puliti, moderni e comfortevoli. Vi aiutiamo con i vostri bagagli e ci adattiamo flessibilmente alle vostre esigenze.</p><h2><strong>Monitoraggio dei voli e tempo d'attesa</strong></h2><p>I ritardi dei voli non sono un problema. Monitoriamo il vostro volo in tempo reale e regoliamo automaticamente l'ora del prelievo. Ricevete anche 60 minuti di tempo d'attesa gratuito all'aeroporto di Vienna.</p><h2><strong>Prezzi fissi senza costi nascosti</strong></h2><p>Tutti i prezzi dei taxi dell'aeroporto vengono visualizzati in anticipo, senza sorprese, senza costi aggiuntivi. Il prezzo include il prelievo in aeroporto, il tempo d'attesa, il servizio bagagli e il monitoraggio del volo.</p>`
    },
    "private-chauffeur-vienna": {
      title: "Autista privato a Vienna",
      desc: "Servizio di autista privato di lusso a Vienna con soluzioni di trasporto personalizzate, discrete e flessibili.",
      longDesc: `<h1><strong>Autista privato a Vienna</strong></h1><p>Assumere un autista privato a Vienna è la soluzione ideale per i viaggiatori che apprezzano il comfort, l'affidabilità e un'esperienza di viaggio completamente personalizzata.</p><p>Che necessitiate di una corsa da un punto all'altro all'interno della città, di un autista per l'intera giornata, di supporto per i viaggi d'affari, o di trasferimenti a lunga distanza all'interno dell'Austria e dei paesi vicini, i nostri autisti professionisti garantiscono viaggi fluidi e senza stress.</p><h2><strong>Viaggio confortevole e senza stress</strong></h2><p>Un autista privato vi offre la massima flessibilità. Nessuna attesa, nessuna coda, nessuna ricerca di taxi. Il vostro autista arriva esattamente quando e dove lo necessite, fornendo un servizio porta a porta confortevole. I nostri veicoli sono moderni, ben mantenuti e perfettamente equipaggiati per i viaggi brevi e lunghi.</p><h2><strong>Perfetto per i clienti aziendali e societari</strong></h2><p>Vienna è uno dei più importanti centri economici e congressuali dell'Europa centrale. Con un autista privato, potete viaggiare in modo efficiente tra riunioni, conferenze, hotel e l'aeroporto di Vienna senza sprecare tempo prezioso. I nostri autisti sono discreti, puntuali e appositamente addestrati a fornire un servizio ottimale.</p><h2><strong>Servizio personalizzato per ogni occasione</strong></h2><p>Che si tratti di una visita familiare, di un'occasione speciale, di una spedizione di shopping o di sightseeing a Vienna e nei suoi dintorni, il vostro autista privato si adatterà flessibilmente ai vostri piani. Seggiolini per bambini, spazio di stoccaggio aggiuntivo o viaggi con più fermate sono disponibili su richiesta.</p>`
    }
  },
  de: {
    "private-day-tours": {
      title: "Private Tagestouren",
      desc: "Private Tagestouren von Wien nach Österreich und Nachbarländer.",
      longDesc: `<h1><strong>Private Tagestouren</strong></h1><p>Unsere privaten Tagestouren von Wien bieten die perfekte Gelegenheit, die schönsten Ziele Österreichs und der Nachbarländer in aller Ruhe und in Ihrem eigenen Tempo zu erkunden.</p><p>Genießen Sie eine entspannte Fahrt mit privatem Fahrer von Wien, spaciosem Fahrzeug und vollständiger Flexibilität während des gesamten Tages.</p><h2><strong>Entdecken Sie Österreich in Komfort</strong></h2><p>Österreich bietet atemberaubende Landschaften und weltweit renommierte Ziele, ideal für private Tagestouren. Beliebte Ziele sind Salzburg, Hallstatt, das Wachau-Tal, Melk, Graz, die Österreichischen Alpen und Tagesausflüge nach Bratislava oder Budapest.</p><h2><strong>Ihr Zeitplan, Ihre Route</strong></h2><p>Bei einer privaten Tagestour entscheiden Sie, wie Ihr Tag ablaufen wird. Verbringen Sie so viel Zeit wie gewünscht an jeder Haltestelle, fügen Sie zusätzliche Ziele hinzu oder passen Sie Ihre Route unterwegs flexibel an. Ihr Fahrer unterstützt Ihre Pläne und garantiert eine sanfte und angenehme Erfahrung.</p><h2><strong>Festpreise und vollständige Flexibilität</strong></h2><p>Alle Preise für private Tagestouren werden transparent im Voraus angezeigt, ohne Überraschungen.</p>`
    },
    "vienna-airport-taxi": {
      title: "Wien Flughafen Taxi",
      desc: "Schneller, sicherer und zuverlässiger Taxi-Service zwischen dem Flughafen Wien (VIE) und einem beliebigen Ziel in Wien oder ganz Österreich.",
      longDesc: `<h1><strong>Wien Flughafen Taxi</strong></h1><p>Unser Taxi-Service am Flughafen Wien bietet eine schnelle, sichere und zuverlässige Möglichkeit zu reisen zwischen Flughafen Wien (VIE) und einem beliebigen Ziel in der Stadt oder in ganz Österreich.</p><p>Ob Sie nach einem langen Flug ankommen oder zum Flughafen für Ihren Abflug reisen – unsere professionellen Fahrer garantieren eine sanfte und stressfreie Fahrt von Anfang bis Ende.</p><p>Vermeiden Sie das Warten auf öffentliche Verkehrsmittel oder die Suche nach einem Taxi. Ihr Fahrer ist genau dann bereit, wenn Sie ihn brauchen.</p><h2><strong>Komfortable Flughafentransfers</strong></h2><p>Mit unserem Flughafen-Taxi-Service genießen Sie einen direkten Haustür-zu-Haustür-Service in sauberen, modernen und komfortablen Fahrzeugen. Wir helfen Ihnen mit Ihrem Gepäck und passen uns flexibel Ihren Bedürfnissen an.</p><h2><strong>Live-Flugverfolgung und Wartezeit</strong></h2><p>Flugverspätungen sind kein Problem. Wir verfolgen Ihren Flug live und passen die Abholzeit automatisch an. Sie erhalten auch 60 Minuten kostenlose Wartezeit am Flughafen Wien.</p><h2><strong>Festpreise ohne versteckte Gebühren</strong></h2><p>Alle Flughafen-Taxi-Preise werden im Voraus angezeigt, ohne Überraschungen, ohne Zusatzkosten. Der Preis beinhaltet die Abholung am Flughafen, Wartezeit, Gepäckservice und Flugverfolgung.</p>`
    },
    "hotel-transfers-vienna": {
      title: "Hoteltransfers Wien",
      desc: "Zuverlässige und komfortable Hoteltransfers in Wien und der Umgebung mit modernen Fahrzeugen.",
      longDesc: `<h1><strong>Hoteltransfers Wien</strong></h1><p>Unser Hoteltransfer-Service in Wien bietet eine zuverlässige und komfortable Lösung für Ihre Anreise und Abreise von Ihrem Hotel.</p><p>Von Ihrer Ankunft am Flughafen bis zu Ihrer Abreise zum Flughafen – unsere Fahrer sorgen für einen schnellen, sicheren und komfortablen Transfer, damit Sie entspannen und Ihre Reise genießen können.</p><h2><strong>Komfortable und zuverlässige Transfers</strong></h2><p>Mit unserem Hoteltransfer-Service reisen Sie in geräumigen, gut gepflegten und modernen Fahrzeugen. Unsere professionellen Fahrer kennen Wien und die beste Route perfekt, um Sie pünktlich zu Ihrem Ziel zu bringen.</p><h2><strong>Für alle Arten von Gästen</strong></h2><p>Ganz gleich, ob Sie als Familie mit Kindern, als Geschäftsreisender, als Paar oder mit einer Gruppe reisen – unser Hoteltransfer-Service passt sich Ihren Bedürfnissen an. Kinder sitzen zur Verfügung und zusätzlicher Platz für Gepäck ist kein Problem.</p><h2><strong>Transparente Preise</strong></h2><p>Alle Hoteltransfer-Preise werden transparent vor der Buchung angezeigt, ohne versteckte Gebühren und ohne Überraschungen.</p>`
    },
    "long-distance-transfers": {
      title: "Fernfahrten",
      desc: "Komfortable und zuverlässige Fernfahrten von Wien nach ganz Österreich und Nachbarländer.",
      longDesc: `<h1><strong>Fernfahrten</strong></h1><p>Unser Fernfahrt-Service bietet komfortable und zuverlässige Transfers von Wien zu Zielen überall in Österreich und in den Nachbarländern.</p><p>Egal wohin Sie fahren müssen – Salzburg, Graz, Vorarlberg, die Schweiz, Bayern oder nach Budapest – wir kümmern uns um einen sicheren, komfortablen und effizienten Transfer.</p><h2><strong>Komfortable und sichere Langstrecken</strong></h2><p>Auf langen Fahrten ist Komfort das Wichtigste. Unsere Fahrzeuge sind mit moderner Ausstattung, verstellbaren Sitzen, WiFi und anderen Annehmlichkeiten ausgestattet, um Ihre Fahrt so angenehm wie möglich zu gestalten.</p><h2><strong>Für alle Arten von Reisen</strong></h2><p>Egal ob Geschäftsreise, Familienurlaub, Partnerabenteuer oder Abenteuer mit Freunden – unsere erfahrenen Fahrer stellen sicher, dass Ihre Langstreckenfahrt entspannt, sicher und effizient ist.</p><h2><strong>Festpreise für Fernfahrten</strong></h2><p>Alle Fernfahrt-Preise werden vor Reisebeginn fixiert. Sie kennen die genauen Kosten im Voraus – ohne versteckte Gebühren.</p>`
    },
    "private-day-tours-oebb": {
      title: "Luxus Reisen",
      desc: "Luxusreisen in und um Wien mit privatem Fahrer und exklusiven Erlebnissen.",
      longDesc: `<h1><strong>Luxusreisen</strong></h1><p>Unsere Luxusreisen in Wien bieten Ihnen exklusive Erlebnisse und den höchsten Standard von Service und Komfort.</p><p>Mit privatem Fahrer und modernen, luxuriösen Fahrzeugen erkunden Sie Wien und die Umgebung in vollständiger Eleganz und Ruhe.</p><h2><strong>Exklusive Erlebnisse</strong></h2><p>Von VIP-Stadtrundfahrten über Besuche in den besten Restaurants bis hin zu Private-Shopping-Touren – wir kümmern uns um alle Details für Ihr Luxuserlebnis.</p><h2><strong>Perfekt für besondere Anlässe</strong></h2><p>Hochzeitsfahrten, Jubiläen, Geschäftsereignisse oder andere besondere Gelegenheiten verdienen einen außergewöhnlichen Service. Wir machen es möglich.</p><h2><strong>Vollständig personalisiert</strong></h2><p>Jedes Luxus-Reiseerlebnis ist vollständig nach Ihren Wünschen zugeschnitten – Zeitplan, Ziele, Verpflegung, alles genau wie Sie es wünschen.</p>`
    },
    "executive-transfers": {
      title: "Executive Transfers",
      desc: "Professionelle Executive Transfers für Geschäftsreisende und Führungskräfte in Wien.",
      longDesc: `<h1><strong>Executive Transfers</strong></h1><p>Unser Executive Transfer Service ist die ideale Lösung für anspruchsvolle Geschäftsreisende und Führungskräfte, die professionelle, diskrete und zuverlässige Transferservices benötigen.</p><p>Von Besprechungen, Konferenzen bis zu Geschäftsreisen – unsere Fahrer stellen sicher, dass Sie stets pünktlich, entspannt und professionell ankommen.</p><h2><strong>Professionel und diskret</strong></h2><p>Unsere Fahrer sind speziell geschult, höchste Professionalität und Diskretion zu gewährleisten. Absolute Vertraulichkeit ist garantiert.</p><h2><strong>Effiziente Geschäftsreisen</strong></h2><p>Mit Executive Transfers sparen Sie wertvolle Zeit und können sich während der Fahrt auf Ihre Arbeit konzentrieren oder einfach entspannen.</p><h2><strong>Flughafentransfers und mehr</strong></h2><p>Ob Flughafentransfers, Transfers zwischen Meeting-Orten oder zur Hotel – unser Service ist vollständig auf Ihre Geschäftsanforderungen zugeschnitten.</p>`
    },
    "group-transfers": {
      title: "Gruppentransfers",
      desc: "Zuverlässige und komfortable Gruppentransfers für Reiseveranstalter, Schulen und Unternehmen.",
      longDesc: `<h1><strong>Gruppentransfers</strong></h1><p>Unser Gruppentransfer-Service ist ideal für Reiseveranstalter, Schulen, Unternehmen und Organisationen, die zuverlässige Transportlösungen für Gruppen benötigen.</p><p>Wir verwalten Transporte für Gruppen jeder Größe – von kleinen Gruppen bis zu großen Busgruppen – mit Professionalism, Zuverlässigkeit und Komfort.</p><h2><strong>Spezialisiert auf Gruppen</strong></h2><p>Wir haben umfangreiche Erfahrung mit Gruppentransporten und kennen alle Aspekte von Logistik, Koordination und Zeitmanagement für große Gruppen.</p><h2><strong>Flexible Lösungen</strong></h2><p>Von Flughafentransfers für Gruppen über Stadtrundfahrten bis zu mehrtägigen Touren – wir bieten flexible Lösungen, die genau auf Ihre Anforderungen abgestimmt sind.</p><h2><strong>Sichere und komfortable Fahrzeuge</strong></h2><p>Alle unsere Fahrzeuge erfüllen höchste Sicherheitsstandards und sind perfekt für Gruppentransporte ausgestattet.</p>`
    },
    "vip-services": {
      title: "VIP Services",
      desc: "Exklusive VIP-Services mit privatem Chauffeur und Concierge-Service in Wien.",
      longDesc: `<h1><strong>VIP Services</strong></h1><p>Unsere VIP-Services bieten die höchste Stufe von Luxus, Komfort und Exklusivität für anspruchsvolle Gäste in Wien.</p><p>Mit privatem Chauffeur, persönlichem Concierge-Service und zugeschnittenem Erlebnis wird Ihr Aufenthalt in Wien unvergesslich.</p><h2><strong>Luxus und Exklusivität</strong></h2><p>VIP-Transfers, private Stadttouren, Reservierungen in den besten Restaurants, Tickets für Veranstaltungen – alles wird für Sie organisiert.</p><h2><strong>Professionelle Diskretion</strong></h2><p>Vollständige Vertraulichkeit und professionelle Diskretion sind garantiert. Ihre Privatsphäre ist unsere Priorität.</p><h2><strong>24/7 Verfügbarkeit</strong></h2><p>Unser VIP-Service ist rund um die Uhr verfügbar, um all Ihre Bedürfnisse zu erfüllen.</p>`
    },
    "vienna-airport-taxi-fixed-rate": {
      title: "Wien Flughafen Taxi",
      desc: "Schneller, sicherer und zuverlässiger Taxi-Service zwischen dem Flughafen Wien (VIE) und einem beliebigen Ziel in Wien oder ganz Österreich.",
      longDesc: `<h1><strong>Wien Flughafen Taxi</strong></h1><p>Unser Taxi-Service am Flughafen Wien bietet eine schnelle, sichere und zuverlässige Möglichkeit zu reisen zwischen Flughafen Wien (VIE) und einem beliebigen Ziel in der Stadt oder in ganz Österreich.</p><p>Ob Sie nach einem langen Flug ankommen oder zum Flughafen für Ihren Abflug reisen – unsere professionellen Fahrer garantieren eine sanfte und stressfreie Fahrt von Anfang bis Ende.</p><p>Vermeiden Sie das Warten auf öffentliche Verkehrsmittel oder die Suche nach einem Taxi. Ihr Fahrer ist genau dann bereit, wenn Sie ihn brauchen.</p><h2><strong>Komfortable Flughafentransfers</strong></h2><p>Mit unserem Flughafen-Taxi-Service genießen Sie einen direkten Haustür-zu-Haustür-Service in sauberen, modernen und komfortablen Fahrzeugen. Wir helfen Ihnen mit Ihrem Gepäck und passen uns flexibel Ihren Bedürfnissen an.</p><h2><strong>Live-Flugverfolgung und Wartezeit</strong></h2><p>Flugverspätungen sind kein Problem. Wir verfolgen Ihren Flug live und passen die Abholzeit automatisch an. Sie erhalten auch 60 Minuten kostenlose Wartezeit am Flughafen Wien.</p><h2><strong>Festpreise ohne versteckte Gebühren</strong></h2><p>Alle Flughafen-Taxi-Preise werden im Voraus angezeigt, ohne Überraschungen, ohne Zusatzkosten. Der Preis beinhaltet die Abholung am Flughafen, Wartezeit, Gepäckservice und Flugverfolgung.</p>`
    }
  }
} as const;

